# Generated by Django 5.1.1 on 2024-09-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('close_register_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('location', models.TextField()),
                ('platform', models.TextField()),
                ('activity_type', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=10)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('contact', models.TextField()),
                ('is_approve', models.CharField(choices=[('approval', 'Approval'), ('approved', 'Approved'), ('reject', 'Reject')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateField()),
                ('role', models.CharField(choices=[('Participant', 'Participant'), ('Organizer', 'Organizer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_web.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_web.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('score', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_web.activity')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'Participant'}, on_delete=django.db.models.deletion.CASCADE, to='event_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_web.category')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'Participant'}, on_delete=django.db.models.deletion.CASCADE, to='event_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': 'Organizer'}, on_delete=django.db.models.deletion.CASCADE, to='event_web.user'),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_web.category')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'Participant'}, on_delete=django.db.models.deletion.CASCADE, to='event_web.user')),
            ],
        ),
    ]
